#!/usr/bin/env bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/test_espnet/espnet_mlu/tools/python_user_base"
export PATH="/test_espnet/espnet_mlu/tools/python_user_base/bin":${PATH}
export PATH=/torch/venv3/pytorch/bin:${PATH}
