ARG FROM_IMAGE_NAME=yellow.hub.cambricon.com/pytorch/pytorch:v1.3.0-torch1.9-ubuntu18.04
FROM ${FROM_IMAGE_NAME}

COPY ./run_scripts/*.sh /torch/src/pytorch_models/Training/Classification/vision_classification/

WORKDIR /torch/src/pytorch_models/Training/Classification/vision_classification
